<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Teos.OpportunityNetwork.Core</RootNamespace>
    <AssemblyName>Teos.OpportunityNetwork.Core</AssemblyName>
  </PropertyGroup>
</Project>
